### ISSUE TITLE
Using the replica.com API?

### ISSUE THREAD

**Issue by nomeata** [blueturtleai/gimp-stable-diffusion#11]
I’d like to play around with gimp and stable diffusion, but wish the setup was a bit simpler.

So far, I am experimenting with stable diffusion through https://replicate.com/stability-ai/stable-diffusion and their quite simple [python API](https://github.com/replicate/replicate-python), and could image that to be a good fit for the gimp plugin as well, as an alternative to the Google-hosted runner.

Would you consider that as a backend?

**Comment by blueturtleai** [comment]
Thanks for the suggestion. I will check this later.

If you want to do only text2img, you could generate images for free and without seeting up a colab notebook or a local server. Check out the plugin which uses stablehorde as backend: https://github.com/blueturtleai/gimp-stable-diffusion/tree/main/stablehorde

**Comment by nomeata** [comment]
Ah, nice

I guess all these backends are relatively similar, so adapting the plugin (or supporting multiple backends in one plugin) shouldn't be that hard.

**Comment by blueturtleai** [comment]
I already had a quick look at replicate. It seems, they don't have a free tier like colab, but you can try it for free. Do you know how much GPU time you can use before you are required to pay?

**Comment by nomeata** [comment]
I maybe ran 100 generations before it asked me to pay? But I didn't keep precise track

**Comment by blueturtleai** [comment]
I had a look now at replicate.com. I don't plan to support it. The reason is, that they don't have a free tier like Colab. Imo people don't want to use a service for which they have to pay. So, I currently don't see enough demand for such a plugin. I also talked to a krita/photoshop stable diffusion plugin developer. He also sees no demand.

Is it right, that you currently pay for generating on replicate.com as your free generations are already gone? In this case, you could also use https://beta.dreamstudio.ai. It is run by stability, I think they are a bit cheaper and they have now a pretty good webui.

**Comment by nomeata** [comment]
Thanks for considering this nevertheless!

**Comment by nomeata** [comment]
So I wanted to try your plugin, but my google drive didn't have the left-over space, and the stablehorde doesn’t do img2img yet, so I created a fork supporting replicate.com after all – linking this here in case people find this issue via Google.

https://github.com/nomeata/gimp-stable-diffusion

(I am personally not attached to replicate.com, it just seemed _one_ way to get the generations to run very hassle-free :-).

I hope eventually a single well-maintainted plugin will just support various backends.

**Comment by blueturtleai** [comment]
Thanks for the update. I released three hours ago a new variant of my plugin. It's for running a server locally. The server is set up using cog, which was developed by replicate :). So, it's the replicate stable-diffusion server running locally but with a different API.

I don't know, if it's hassle-free, but if you would like to give it a try, you find it here: https://github.com/blueturtleai/gimp-stable-diffusion/tree/main/local.
