### ISSUE TITLE
HTTPError 524

### ISSUE THREAD

**Issue by Ulfzerk** [blueturtleai/gimp-stable-diffusion#12]
Hi!

I'm trying to check out this plugin. 
Unfortunatly i always get HTTP error 524. 
`Traceback (most recent call last):
  File "C:\Program Files\GIMP 2\lib\gimp\2.0\python/gimpfu.py", line 741, in response
    dialog.res = run_script(params)
  File "C:\Program Files\GIMP 2\lib\gimp\2.0\python/gimpfu.py", line 362, in run_script
    return apply(function, params)
  File "C:\Users\user\AppData\Roaming\GIMP\2.10\plug-ins\gimp-stable-diffusion.py", line 102, in img2img
    raise ex
HTTPError: HTTP Error 524: 
`

I tried to rise time-out in 
`
response = urllib2.urlopen(request,timeout = 30*60)
`
But it didn't work.

**Comment by blueturtleai** [comment]
Could you please enter the cloudflare root URL in a browser and check what happens then?

**Comment by Ulfzerk** [comment]
`INFO:werkzeug: * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
 * Running on https://highland-battle-bosnia-proud.trycloudflare.com/
 * Traffic stats available on http://127.0.0.1:8099/metrics
INFO:werkzeug:127.0.0.1 - - [14/Oct/2022 11:48:45] "GET / HTTP/1.1" 404 -
INFO:werkzeug:127.0.0.1 - - [14/Oct/2022 11:48:45] "GET /favicon.ico HTTP/1.1" 404 -
INFO:werkzeug:127.0.0.1 - - [14/Oct/2022 11:48:46] "GET / HTTP/1.1" 404`

Basicly when I send a request with gimp there is a print that says that request has been recived. But after like 100 sec there is a 524 error form a gimp side. After this error colab env is still computing it. 
![image](https://user-images.githubusercontent.com/26842884/195840654-c0a54c8b-3e32-40be-a237-345b8111c9b2.png)

**Comment by blueturtleai** [comment]
Hm, that's strange. Normally you should see a progressbar below "Batch 1 of 1" and at the end a HTTP code 200 when the image was sent back. For some reason the image generation doesn't start. The result is the timeout because GIMP doesn't receive the image.

Did all the steps before execute without errors?

**Comment by blueturtleai** [comment]
Especially the first step. What is displayed when you execute the first step (NVIDIA GPU)? Tbh, I don't know exactly what happens, if you don't get a GPU.

**Comment by Ulfzerk** [comment]
I figured it out. 
As you can see on screen shot above i tried to pass a quite big picture to model. Model was supossed to work on it for like 20 minutes instead of few secounds, it worked as intended on 512x512 img size. 
Probably there is a limit on requests somewhere else. (cloudfire?) 
I would have to try it locally on a bigger picture but unfortunatly i don't have possibility to do so.

**Comment by blueturtleai** [comment]
Great you found the reason. I think the GPU, which is available in the free colab plan, is too slow for such big images. Tbh, I would have expected it failed with out of memory error.
