### ISSUE TITLE
Unable to generate image on Stablehorde version due to URL error

### ISSUE THREAD

**Issue by planetfrog** [blueturtleai/gimp-stable-diffusion#13]
Tried installing on Win 10 Pro - installed stable-horde ok - showed up on menu in Gimp.... but cannot generate image: 

Error: "Ab error occurred runing python-fu-img2img
ValueError: Unknown url type: /api/img2img

------------------------

Traceback (most recent call last):
  File "C:\Program Files\GIMP 2\lib\gimp\2.0\python/gimpfu.py", line 741, in response
    dialog.res = run_script(params)
  File "C:\Program Files\GIMP 2\lib\gimp\2.0\python/gimpfu.py", line 362, in run_script
    return apply(function, params)
  File "C:\Users\Trader\AppData\Roaming\GIMP\2.10\plug-ins\gimp-stable-diffusion.py", line 102, in img2img
    raise ex
ValueError: unknown url type: /api/img2img

**Comment by blueturtleai** [comment]
Which version of the plugin do you use? You can see the version at the top of the python file. It should be version 1.2.0.

**Comment by blueturtleai** [comment]
I assume, you installed the wrong type of the plugin. If you want to use stablehorde, you need to install the plugin from the subfolder "stablehorde". https://github.com/blueturtleai/gimp-stable-diffusion/tree/main/stablehorde

**Comment by planetfrog** [comment]
> I assume, you installed the wrong type of the plugin. If you want to use stablehorde, you need to install the plugin from the subfolder "stablehorde". https://github.com/blueturtleai/gimp-stable-diffusion/tree/main/stablehorde

Thank you, yes you were absolutely correct. I've reinstaled it and its now working ! Thanks for your help - this is a bit new to me.
