### ISSUE TITLE
Support for SD v1.5?

### ISSUE THREAD

**Issue by zuencap** [blueturtleai/gimp-stable-diffusion#14]
Hi, is 1.5 supported? It isn't available in the model_map.

**Comment by blueturtleai** [comment]
Do you mean in the notebook? Just checked the deforum notebook on which the gimp notebook is based. They didn’t add 1.5 until now, don’t know why. I will check if it can be added and if it’s possible, I will do.

**Comment by blueturtleai** [comment]
The notebook supports SD 1.5 now.
