### ISSUE TITLE
Inpainting for local server

### ISSUE THREAD

**Issue by nilsmelchert** [blueturtleai/gimp-stable-diffusion#15]
Hi,
I was wondering, when the inpainting option for the local server will be available as a feature?

**Comment by blueturtleai** [comment]
I just checked the newest version of cog-stable-diffusion. They are using not the newest version of the diffusers inpainting pipeline. So, i don’t know how good inpainting quality will be. But I will update in the next few days.

**Comment by blueturtleai** [comment]
Inpainting is available now. Please update your plugin and also rebuild your server.

**Comment by nilsmelchert** [comment]
Thanks!
