### ISSUE TITLE
Colab notebook seems to be out-of-date

### ISSUE THREAD

**Issue by thndrbrrr** [blueturtleai/gimp-stable-diffusion#16]
I was able to make it work, but the Colab server and `gimp-stable-diffusion-local.py` are not in sync. For example, the plugin is looking for the API endpoint `/predictions` wheras Flask serves the requests under `/api/generate`. There are various other mismatches as well in the data structures (keys missing etc.)

Just wondering if there's an updated Colab somewhere? Otherwise happy to share the changes I made to make it work again.

Thanks! :)

**Comment by blueturtleai** [comment]
It seems you used the wrong plugin. The plugin which works together with the notebook is located in the main directory and not in the local subdirectory. https://github.com/blueturtleai/gimp-stable-diffusion/blob/main/gimp-stable-diffusion.py

**Comment by thndrbrrr** [comment]
Oh man ... I don't even ... LOL

![homer](https://user-images.githubusercontent.com/3769545/202915443-d1df53ea-62d2-44b1-a46c-1aec187bd41e.png)
