### ISSUE TITLE
file_webp_load error in stablehorde flavor

### ISSUE THREAD

**Issue by jaimevives** [blueturtleai/gimp-stable-diffusion#18]
Hi, first of all, thanks for such amazing plugins. The main one for colab is working great, but then I tried the stablehorde one and is giving me an error when trying to show the generated image. It says it cannot find file_webp_load... I guess it's because my gimp 2.8 version doesn't supports webp. Is there a workaround, or do i've to install gimp 2.10?

Regards,

**Comment by blueturtleai** [comment]
I just checked. It seems that webp is supported since 2.10. So, unfortunately it‘s necessary, that you install this version. I will update the readme, that 2.10 is needed.

**Comment by blueturtleai** [comment]
It seems, that stablehorde is currently pretty slow due to many requests. They are currently working on solving the problem.

**Comment by jaimevives** [comment]
OK, thanks... will upgrade asap. Regards,
