### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: './externals/Next_ViT/classification/nextvit.py'

### ISSUE THREAD

**Issue by jaimevives** [blueturtleai/gimp-stable-diffusion#19]
When running the python definitions, I get this error:
---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)

[<ipython-input-5-61647615b422>](https://localhost:8080/#) in <module>
     36 import py3d_tools as p3d
     37 
---> 38 from helpers import DepthModel, sampler_fn
     39 from k_diffusion.external import CompVisDenoiser
     40 from ldm.util import instantiate_from_config

4 frames

[/content/MiDaS/midas/backbones/next_vit.py](https://localhost:8080/#) in <module>
      6 from .utils import activations, forward_default, get_activation
      7 
----> 8 file = open("./externals/Next_ViT/classification/nextvit.py", "r")
      9 source_code = file.read().replace(" utils", " externals.Next_ViT.classification.utils")
     10 exec(source_code)

FileNotFoundError: [Errno 2] No such file or directory: './externals/Next_ViT/classification/nextvit.py'
---------------------------------------------------------------------------

It's just me or there is a problem with the colab notebook?

Regards,

**Comment by blueturtleai** [comment]
Thanks for the error report. I could reproduce the problem. Need to check how this can be fixed.

**Comment by blueturtleai** [comment]
I had a look now. It seems there is no easy fix. My notebook is based on the deforum notebook, which fails now with the same error (deforum notebook 0.5). It exists now version 0.6, which uses a completely new "architecture", so there is no easy way to adapt my notebook. I have to investigate this further to find out, how the problem can be solved.

Unfortunately, for now I can only suggest to use one of the other flavours of my plugin: stablehorde or local install.

**Comment by jaimevives** [comment]
Oh, well... I was fearing something like that. I can still use other tools, though this Gimp plugin was really convenient. Thanks for the great work... it was really fun while it lasted.

**Comment by blueturtleai** [comment]
### Discontinued
The GIMP plugin notebook was based on the deforum notebook. As this notebook is broking now, the GIMP plugin notebook doesn't work any longer either. To make it working again, a complete rewrite would be necessary. This would happen in the future again again. For this reason and combined with the fact that the usage of the GIMP notebook seems to be pretty low, the GIMP plugin for colab will be discontinued. Please check out the [GIMP plugin, which uses stablehorde](https://github.com/blueturtleai/gimp-stable-diffusion/tree/main/stablehorde) as an alternative.
