### ISSUE TITLE
import urllib2

### ISSUE THREAD

**Issue by icf20** [blueturtleai/gimp-stable-diffusion#21]
please not this require python2

**Comment by blueturtleai** [comment]
GIMP 2 is based on python 2. On Windows/Mac it’s included in the setup. If you are on Linux and run into problems, please check the troubleshooting section in the readme.

**Comment by icf20** [comment]
Python 2 is not longer maintained, installing that should be a big nope

**Comment by blueturtleai** [comment]
Okay, I see. Are you on Linux?

**Comment by kozec** [comment]
It may help if you use py2-specific shebang

```diff
-#!/usr/bin/python
+#!/usr/bin/env python2
```

Sadly, python incorrectly defaults to python3 on Arch and Fedora-based distros.
