### ISSUE TITLE
plugin not working in windows

### ISSUE THREAD

**Issue by shawn-j** [blueturtleai/gimp-stable-diffusion#22]
I followed the instructions, and didn't see an "AI" menu.  there's no troubleshooting options for windows.  what additional info do you need?  thanks

**Comment by blueturtleai** [comment]
Please check, if you can run "Filters > Render > Spyrogimp". This plugin is also Python based. If this also doesn’t work, there is a general problem with your GIMP installation.

**Comment by blueturtleai** [comment]
As i didn’t hear from you for several days, I’m closing the issue now.
