### ISSUE TITLE
if you don't mind can tell me when gimp 3 port will come ?

### ISSUE THREAD

**Issue by Anikmoujegy** [blueturtleai/gimp-stable-diffusion#23]
According to the last blog post of official gimp website, the gimp 3.0 will be released soon in 2023 at least a release candidate and as I used the latest beta most of the work is almost done so it will be great if new port of the plug-in release soon. :)

**Comment by blueturtleai** [comment]
AFAIK especially the plugins are the reason why 3.0 is still not released. They announce now for a very long time, that 3.0 will be released soon. As soon as this is the case, I will port the plugin to 3.0.

**Comment by Anikmoujegy** [comment]
ok
