### ISSUE TITLE
Add upscaling support with AI

### ISSUE THREAD

**Issue by Anikmoujegy** [blueturtleai/gimp-stable-diffusion#24]
As stable diffusion also support image upscaling it will great to have this feature.
And a guy called AgileDevArt has already added the feature to his version of the plug-in.
link of his version of the plug-in : https://github.com/AgileDevArt/stable-diffusion-plugins
He also made a video on this : https://www.youtube.com/watch?v=bN8nLvSsYd0

**Comment by blueturtleai** [comment]
I just checked the upscaling in the mentioned plugin. It doesn’t use stable diffusion, but GIMP. So, just use GIMP directly, if you want to upscale 😀. 

If you want to upscale more than possible with GIMP, please use the other plugin. I won’t support it, as I think that very few want to upscale that much.
