### ISSUE TITLE
Problem in Linux

### ISSUE THREAD

**Issue by ABS6x** [blueturtleai/gimp-stable-diffusion#26]
I have moved the folder stablehorde from the zip inside the local Gimp folder, i have change the permission, but when i restart Gimp i not see the AI menu.

if i try to run the plugin py manually this is the result:

~/.config/GIMP/2.10/plug-ins$ python gimp-stable-diffusion.py python: can't open file '~/.config/GIMP/2.10/plug-ins/gimp-stable-diffusion.py': [Errno 2] No such file or directory

**Comment by blueturtleai** [comment]
You want to run the stablehorde variant, which is located here? https://github.com/blueturtleai/gimp-stable-diffusion/tree/main/stablehorde

If so, you use the wrong filename. The name is „gimp-stable-diffusion-horde.py.“

**Comment by ABS6x** [comment]
You right i'm trying with the wrong name file.
I let start the plugin with the correct name and i have this problem
"No module named 'urllib2'"
I have used 2to3 to correct this (https://pypi.org/project/2to3/) and now i've a new one
If i start the plugin from terminal using "python gimp-stable-diffusion-horde.py"
this is the result

Traceback (most recent call last):
  File "/home/andrea/Programmi/Gimp/gimp-stable-diffusion-main/stablehorde/gimp-stable-diffusion-horde.py", line 13, in <module>
    import gimp
ModuleNotFoundError: No module named 'gimp'

**Comment by blueturtleai** [comment]
I don’t know 2to3, but you need python 2 to run the plugin.

„Gimp“ can’t be found, if you run it on the command line, as this is only available, if you run the plugin inside of gimp.

**Comment by blueturtleai** [comment]
As i didn’t hear from you for some days, I close this issue. Please reopen it, if you like to resolve the issue.
