### ISSUE TITLE
Compatibility with PortableApps.com version of GIMP

### ISSUE THREAD

**Issue by stephenrgilman** [blueturtleai/gimp-stable-diffusion#27]
I am trying to get the plugin to work with the PortableApps.com version of GIMP, but so far with no luck. The AI/stablehorde menu item does not display.

I have tested the Spyrogimp plugin to ensure that Python is working properly, so that shouldn't be the issue.

I have the plugin saved at \PortableApps\GIMPPortable\Data\.gimp\plug-ins

Any advice you can provide would be appreciated.  Thanks!

**Comment by blueturtleai** [comment]
Please replace the first line in the py file like this and try it again.

#!/usr/bin/env python2

**Comment by blueturtleai** [comment]
As i didn’t hear from you for some days now, I close this issue. If you are interested in solving the issue, please just reopen it.
