### ISSUE TITLE
Ubuntu Local Issues 

### ISSUE THREAD

**Issue by nbollman** [blueturtleai/gimp-stable-diffusion#29]
Not sure what Im doing wrong here.. The ubuntu local version is full of bugs... written for python2?

i(base) jonsnow@TheWall:/usr/lib/gimp/2.0/plug-ins$ python gimp-stable-diffusion-local.py
Traceback (most recent call last):
  File "/usr/lib/gimp/2.0/plug-ins/gimp-stable-diffusion-local.py", line 5, in <module>
    import urllib2
ModuleNotFoundError: No module named 'urllib2'
(base) jonsnow@TheWall:/usr/lib/gimp/2.0/plug-ins$ python2 gimp-stable-diffusion-local.py
Traceback (most recent call last):
  File "gimp-stable-diffusion-local.py", line 13, in <module>
    import gimp
ImportError: No module named gimp

sorry for the ugly formatting... having issues this morning

**Comment by blueturtleai** [comment]
Yes, it’s python2. 

„ImportError: No module named gimp“ occurs, because you run the script on the commandline and not from within GIMP. If it still doesn’t work in GIMP, pls check the troubleshooting section https://github.com/blueturtleai/gimp-stable-diffusion/tree/main/local#troubleshooting

**Comment by blueturtleai** [comment]
As i didn’t hear from you for some days, I close this issue. If you are interesting in solving the issue, pls reopen it.
