### ISSUE TITLE
Doesn't work with gimp 2.10.34-1 on Ubuntu Lunar

### ISSUE THREAD

**Issue by GeniusTechnoMystic** [blueturtleai/gimp-stable-diffusion#30]
Doesn't work with gimp 2.10.34-1 on Ubuntu Lunar

**Comment by blueturtleai** [comment]
Did you check the troubleshooting section? https://github.com/blueturtleai/gimp-stable-diffusion/tree/main/stablehorde#troubleshooting

**Comment by blueturtleai** [comment]
As i didn’t hear from you for some days I‘m closing this issue. If you are interested in resolving the issue pls reopen it.

**Comment by Utopiah** [comment]
Same issue, can confirm that switching to flatpak solves it. Thanks for the work and the follow up.
