### ISSUE TITLE
Instructions make no sense on Huggingface

### ISSUE THREAD

**Issue by JBL1972711** [blueturtleai/gimp-stable-diffusion#31]
I started to follow the instructions for this plugin. Installed in GIMP, plugin loads fine but doeant work without hugginface URL. I went to huggingface & signed up. After that the isntructions do NOT match anything on huggingface. I opened the links provided and nothing is as the instructions here on GitHub are saying. No Tokens, no settings, nothing matches anything that is in the instructions. How does this work? There was no agreement to click either. Either these instructions are way outdated or you missed telling some steps.

**Comment by blueturtleai** [comment]
I just checked it and it works like described. So, you are trying to do a local installation https://github.com/blueturtleai/gimp-stable-diffusion/tree/main/local ?

**Comment by JBL1972711** [comment]
Those instructions are for linux. I am running on windows and it seems like
a lot of developers are flat out forgetting to provide instructions for
windows or just don't care or listen to people when they have issues, like
you are doing now.

**Comment by blueturtleai** [comment]
You did write, you got problems on huggingface and didn’t mention, that you try to run it on Windows.

The instructions are also for Windows running WSL2. Like I wrote in the readme, I didn’t test it on Windows. So, unfortunately I can’t help you, if you run in any Windows specific problems.

**Comment by JBL1972711** [comment]
Your instructions mention WSL2 as if it refers to Windows 11 ONLY and it
seems to imply a distinction you never make. The confusion is in how the
instructions are written. After you mention Windows 11 it is so confusing
you may as well not write anything, but regardless, when you mention
Windows 11 it is literally instructions for how to install everything in
Linux! (Yum is literally a linux command for the terminal) Are you just
going to gaslight me now? Why not give people links (yes links) to a
separate page for EACH OS and two separate pages for Windows 11 and Windows
everything else. That's 4 pages. That way there is NO confusion about which
instructions are for which OS. Otherwise the way things are right now I
would never be able to do anything with any OS. It is a confusing hot mess.
I used to write huge technical instruction manuals with visual aids 20
years ago. Your way of doing that is a nightmare for me.

The problem was not huggingface, it was YOUR instructions when I got to the
huggingface step. I said that from the very beginning, that I was confused
about YOUR instructions. The proper response would be "Well, here are the
correct instructions typed out, sorry" Instead I waste time arguing with
you when it is painfully obvious your instructions suck horribly for
anything besides linux and Mac.I mean if you hate windows users then just
say so in your GitHub. Or if you hate Windows just say so. I hate it but I
still use it for some things. But I still need coherent instructions for
using things like this plugin in windows.

TBH, I found out that the GMIC plugin has an inpaint feature that is
lightning fast, simply by masking off an area, and it was not nearly the
headache your plugin is. I had inpainting done faster than I could download
and drop the Stable diffusion python script into my plugins folder.I just
really wanted to see the capabilities of this plugin in case it did a far
better job than the admittedly outdated GMIC plugin which is based on SD
1.4. And the SD 1.4 model is either linked to the GMIC servers or it is
native to the plugin folders. either way it works fast

But please fix your instructions. That's all I am asking. Make them
coherent. Separate them so there is no confusion. Give each OS a separate
page for clarity. And differentiate between Windows 11 and other Windows
OS's.Then people won't be confused about what instructions go to what.

After that, make sure that your instructions for huggungface are still
valid and that they did not change their website so much the instructions
no longer apply. If huggingface can no longer be used, like what happened
with Google, then choose another model to link to, or tell people how they
can add the model of their choice instead.

Or figure out how to link it to free models like this one
https://huggingface.co/spaces/stabilityai/stable-diffusion     which is
free to use anonymously.

or link it to the neural.love model which is free to use or you can sign in
to an account there.

I have no idea how to do any of that but there has to be a work around or a
better way to link to external models.

 And if you develop a plugin then it becomes a full time job to update it,
make clear instructions, and adapt those instructions to be useful to new
users as the web itself changes.

I also wanted to use the local plugin but can't understand how to download
the necessary models to point to on my own PC so I can train or at least
even use the plugin. It gives me the "invalid URL" error every time I
attempt to erase a portion and then inpaint. And I think the image HAS to
be 512x512 which is a really annoying limitation when you want to use it on
larger images or anything twice as wide. I didn't have that limitation with
GMIC.

You are the one who has full control over your product and the
instructions. Telling the end user to figure it out when it is impossible
to figure out is horrible customer service. No wonder most products suck
these days. When people ask for help, the support acts like it's everyone
else's fault.

**Comment by blueturtleai** [comment]
In the readme I write "Linux, macOS and Windows 11 (WSL2) are supported." 

I also write "If you want to run the server on Windows 11, WSL2 needs to be prepared before. Please follow [these instructions](https://github.com/blueturtleai/cog/blob/main/docs/wsl2/wsl2.md) until after you reach executing "wsl.exe" in 7. Afterwards please start with 2. from the instructions below, as Docker is already installed."

I think this is everything, which is needed. It should be possible to install the server with these information.

Unfortunately, I'm not able to give more support beyond that. This is a free plugin, which I programmed in my spare time.

Check also the stablehorde version of my plugin, For this version no local installation is needed: https://github.com/blueturtleai/gimp-stable-diffusion/tree/main/stablehorde.

**Comment by JBL1972711** [comment]
That doesn't work period. Yours is the only one that loads into GIMP. The other ones do not and I have the latest 2.10 version of GIMP installed. I am giving up.
