### ISSUE TITLE
No matter what I do it has an error about the API .key

### ISSUE THREAD

**Issue by Fonseca85** [blueturtleai/gimp-stable-diffusion#39]
It seems no matter what I do, it throw up an error about the API.key, I am using on from stablehorde but still getting no where. Am I doing something wrong? Also the upscaler works great. 

![Screenshot 2024-03-13 142708](https://github.com/blueturtleai/gimp-stable-diffusion/assets/161911723/53659ab1-d48e-425f-a886-b1e5c964a3d0)

**Comment by blueturtleai** [comment]
It seems, you are using a different plugin. Neither stable-horde-t2i.py nor api.key are a part of this repository.
