### ISSUE TITLE
It's for getting an external IP from ngrok.

### ISSUE THREAD

**Issue by heitikei** [blueturtleai/gimp-stable-diffusion#5]
https://github.com/blueturtleai/gimp-stable-diffusion/blob/c8949fbac58a86b2c58d16defaf997064b4ef1d4/gimp-stable-diffusion.py#L70

start_ngrok ngrok_address = _run_ngrok() 

Sorry, I am a natural language programmer using a pen and paper.
Please could swap out appropriate code at lin2 #70?

@blueturtleai

**Comment by blueturtleai** [comment]
This is not possible. Otherwise you won't get an external IP and can't communicate between plugin and server.

**Comment by heitikei** [comment]
Did you try it, or did you think it through mentally?
