### ISSUE TITLE
v1.1.2 load issue

### ISSUE THREAD

**Issue by zuencap** [blueturtleai/gimp-stable-diffusion#6]
Hi, I followed the instruction on the site to install v1.1.2. I get this error and the plugin isn't loaded:
```
Querying plug-in: '/usr/local/abc/home/dfg/.config/GIMP/2.10/plug-ins/gimp-stable-diffusion.py'
gimp: LibGimpBase-WARNING: gimp: gimp_wire_read(): error
Terminating plug-in: '/usr/local/abc/home/dfg/.config/GIMP/2.10/plug-ins/gimp-stable-diffusion.py'
```

**Comment by zuencap** [comment]
I tried v1.1.1. It's the same.

**Comment by blueturtleai** [comment]
Which GIMP version do you use? Which OS? Did you make chmod 755 in case of macOS or Linux?

**Comment by zuencap** [comment]
I use GIMP 2.10.32 on Linux.
Yes the script is executable: 
<pre>-rwxr-xr-x  1 dfg primarygroup 4213 Sep 27 13:58 <font color="#00CD00"><b>gimp-stable-diffusion.py</b></font>*</pre>

**Comment by blueturtleai** [comment]
Currently I don't have an idea why it doesn't work. I will ask the GIMP community and hope to get a solution.

**Comment by blueturtleai** [comment]
Could you please check, if Python 2 is installed on your machine? If not, please install Python 2 and try it again.

**Comment by zuencap** [comment]
I had already python 3. Installed Python 2.7 but it still shows the same message.

I wonder if there is a way to see a more detailed error message.

**Comment by opencoca** [comment]
@zuencap Also, what Linux are you on? I see mention of a similar issue back in [Ubuntu 15.04](https://askubuntu.com/questions/626328/gimp-crashes-in-15-04) though they, too, don't have a conclusive fix.

**Comment by zuencap** [comment]
I use a custom Debian based on the latest version.

**Comment by blueturtleai** [comment]
Please check, if you can run "Filters > Render > Spyrogimp". This plugin is also Python based.

**Comment by blueturtleai** [comment]
Additionally you could check, if the Python console runs. You can open it via "Filters/Python-Fu/Console".

**Comment by zuencap** [comment]
Hmm, I don't have those 😮 I guess I have somehow a reduced GIMP. I'll check if I can get the proper one and update this issue.
Thanks a lot for looking in this.

**Comment by zuencap** [comment]
Looks like Debian doesn't ship gimp-phyton package any more for the sake of Python 3. 
I installed flatpack Gimp:
https://flathub.org/apps/details/org.gimp.GIMP
The plugin loads fine now. Thanks for your help.

**Comment by blueturtleai** [comment]
Great, that it's working now! Do you know if it's necessary to install Python 2 manually or does this happen automatically when you install GIMP from flathub.org?

**Comment by zuencap** [comment]
It works without installing Python2. Flatpak handles everything.

**Comment by opencoca** [comment]
Flat packs are great but they introduce sandboxing that can be complicated
to resolve. I’ll look into this when possible. Can you provide the link to the specific pack?

Edit comment: personal information removed

**Comment by blueturtleai** [comment]
https://flathub.org/apps/details/org.gimp.GIMP
